color: null
fieldLayouts:
  f3827c3a-229f-49a6-ab7a-b689e951095e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-17T15:26:27+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4141ff15-ebbf-4f74-b571-71974b9d59d2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-17T15:29:16+00:00'
            elementCondition: null
            fieldUid: 4246f005-af63-41c2-adfa-04278168a881 # Stories Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: edd41cfb-8b47-4eef-b036-e981b2da73a2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-17T15:29:16+00:00'
            elementCondition: null
            fieldUid: 1f70cb78-6ca2-4a94-b621-6462c2c84094 # Stories Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dfcefc57-2de3-4398-8b41-c850131c37fa
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-17T15:45:19+00:00'
            elementCondition: null
            fieldUid: ded0a65a-f369-4d91-9650-4c5f11f36517 # Stories Entry Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b877d259-86a6-4c95-94a4-9c800921fe77
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 174ef01a-20fb-4ba5-b3e5-32d5abef5e0d
        userCondition: null
handle: stories
hasTitleField: true
icon: null
name: Stories
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
