altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  4dd95213-b3c2-4948-a68a-4fd489488886:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-15T15:04:29+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: d744a3e3-b113-406d-9124-1001a514f085
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f4eeb58b-3435-438a-bb5b-9052d217cd1b
        userCondition: null
fs: uploads
handle: uploads
name: Uploads
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
