columnSuffix: null
handle: navigationText
instructions: null
name: 'Navigation Text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: 'Enter link text'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
