defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 0264e59e-65e6-4039-8a15-aece203b252d # Hero
handle: hero
maxAuthors: 1
name: Hero
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  8182def5-b8ce-4def-902f-7753f324973b: # my-craft-motoventure
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
